update: auto

diff --git a/scripts/mkg b/scripts/mkg
--- a/scripts/mkg
+++ b/scripts/mkg
@@ -2,33 +2,17 @@
 
 set -e
 
-while [[ $# -gt 0 ]]
-do
-  key="${1}"
-
-  case ${key} in
-  -m|--mode)
-    mode="${2}"
-    shift 2
-    ;;
-  -h|--help)
-    echo "mkdir with files"
-    exit 0
-    ;;
-  *)    # unknown option
-    shift # past argument
-    ;;
-  esac
-done
-
-
-if [ -z "$path" ]; then
-  echo 'Missing -h or -u' >&2
+dirname=${1}
+if [[ -d $dirname ]]; then
+  echo -e "\033[31mError: Directory already exists \033[0m" >&2
   exit 1
 fi
-
-dir_name=${1}
+mkdir -pv $dirname  
 shift
 
-echo ${dir_name}
-echo ${@}
+for i in $@; do
+  ln -sv $(pwd)/$i $dirname
+  echo $i
+done
+
+exit 0
